// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'background-black': string;
  'background-red': string;
  'backgroundBlack': string;
  'backgroundRed': string;
  'container': string;
}
declare const cssExports: CssExports;
export = cssExports;
