name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm install
      - run: docker run -d -p 4444:4444 -p 5900:5900 selenium/standalone-chrome-debug
      - run: nohup npm run storybook > out.txt &
      - run: ./health-check http://localhost:9090/
      - run: cat out.txt
      - run: npm test
